---
    name: Lint and Test Code Base
    
    on:
      push:
        branches: [main, collab]
      pull_request:
        branches: [main, collab]
    
    jobs:
      lint_and_test:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout Code
            uses: actions/checkout@v2
    
          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '16'
    
        #   - name: Install Node.js dependencies
        #     run: npm install
    
        #   - name: Run React tests
        #     run: npm test -- --coverage
    
          # - name: Run Super Linter
          #   uses: github/super-linter@v4
          #   env:
          #     VALIDATE_ALL_CODEBASE: true
          #     DEFAULT_BRANCH: main
          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    